# Generated by Django 5.0.6 on 2024-08-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advise',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
