# Generated by Django 5.0.6 on 2024-08-17 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_serves_image_alter_serves_status_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='serves',
            name='api_serves_status_159a54_idx',
        ),
        migrations.RemoveField(
            model_name='serves',
            name='status',
        ),
    ]
