# Generated by Django 5.0.6 on 2024-08-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_comment_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='serves',
            name='reviews',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serves',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
