# Generated by Django 5.0.6 on 2024-08-18 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_serves_reviews_serves_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serves',
            name='reviews',
        ),
    ]
