# Generated by Django 5.0.6 on 2024-08-18 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_serves_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='clients',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='services',
        ),
    ]
