# Generated by Django 5.0.6 on 2024-08-18 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_comment_clients_remove_comment_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='client',
            new_name='clients',
        ),
    ]
