# Generated by Django 5.0.6 on 2024-08-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_client_comment_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advise',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='serves',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
