# Generated by Django 5.0.6 on 2024-08-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_advise_image_alter_clients_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='defination',
            field=models.CharField(default='Default value', max_length=255),
        ),
    ]
