# Generated by Django 5.0.6 on 2024-08-18 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_features_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.serves'),
        ),
    ]
