# Generated by Django 5.0.6 on 2024-08-18 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_features_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='image',
        ),
    ]
