# Generated by Django 5.0.6 on 2024-08-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_features_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serves',
            name='description',
        ),
        migrations.RemoveField(
            model_name='serves',
            name='price',
        ),
        migrations.AddField(
            model_name='serves',
            name='teacher',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
