# Generated by Django 5.0.6 on 2024-08-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_serves_description_remove_serves_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serves',
            name='teacher',
            field=models.CharField(default='Default Teacher', max_length=120),
        ),
    ]
